-- CREATE USER TABLE
CREATE TABLE IF NOT EXISTS userData (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    masterPassword VARCHAR(255) NOT NULL
);

-- CREATE USER PASSWORDS TABLE
CREATE TABLE IF NOT EXISTS userVault (
    id VARCHAR(255) NOT NULL PRIMARY KEY,
    platform VARCHAR(255) NOT NULL,
    encryptedPassword TEXT NOT NULL,
    authTags BLOB NOT NULL,
    iv BLOB NOT NULL,
    userId VARCHAR(255) NOT NULL,
    
    CONSTRAINT user_fk FOREIGN KEY (userId) REFERENCES userData(id) ON DELETE CASCADE);
